# Generated by Django 3.1.7 on 2021-03-31 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('history', models.CharField(max_length=100)),
                ('time', models.TimeField(default=datetime.datetime(2021, 3, 31, 16, 32, 43, 632331))),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('search_by', models.CharField(default='default', max_length=100)),
                ('theme', models.CharField(max_length=5)),
            ],
        ),
    ]
